"""CLI entry point for the OpenRouter Free Model Proxy."""

import argparse
import logging
import os
import sys
from pathlib import Path
from typing import Optional

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)


def _parse_args(argv: Optional[list[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="OpenRouter Free Model Proxy — pools free-tier models"
    )
    parser.add_argument(
        "--host",
        default="127.0.0.1",
        help="Bind address (default: 127.0.0.1)",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=8080,
        help="Bind port (default: 8080)",
    )
    parser.add_argument(
        "--api-key",
        default=os.environ.get("OPENROUTER_API_KEY"),
        help="OpenRouter API key (default: $OPENROUTER_API_KEY)",
    )
    parser.add_argument(
        "--dsh-path",
        help="Path to DSH checkout root (writes config override)",
    )
    parser.add_argument(
        "--keep-alive",
        action="store_true",
        help=(
            "Ping cold models periodically. Off by default: each ping is a "
            "real chat request, and OpenRouter meters free models per request "
            "per day, so pinging exhausts the allowance the pool exists to spend."
        ),
    )
    return parser.parse_args(argv)


def _patch_dsh(dsh_path: str, proxy_url: str) -> None:
    """Write a DSH config override so seats route through this proxy."""
    root = Path(dsh_path)
    config_dir = root / "config"
    config_dir.mkdir(parents=True, exist_ok=True)

    override = config_dir / "openrouter_free.yaml"
    override.write_text(
        f"""# Generated by OpenRouter Free Model Proxy
# Set OPENROUTER_BASE_URL={proxy_url} when launching DSH.
base_url: "${{OPENROUTER_BASE_URL:-{proxy_url}}}"
api_key: "${{OPENROUTER_API_KEY}}"
model: "proxy-auto"
"""
    )
    print(f"[dsh] Wrote config override: {override}")


def main(argv: Optional[list[str]] = None) -> None:
    args = _parse_args(argv)

    if not args.api_key:
        print("Error: OPENROUTER_API_KEY is required.", file=sys.stderr)
        sys.exit(1)

    proxy_url = f"http://{args.host}:{args.port}"

    if args.dsh_path:
        _patch_dsh(args.dsh_path, proxy_url)

    # set env so the app factory picks both up: uvicorn calls it with no
    # arguments, so the environment is the only channel to it.
    os.environ["OPENROUTER_API_KEY"] = args.api_key
    if args.keep_alive:
        os.environ["OPENROUTER_PROXY_KEEP_ALIVE"] = "1"

    import uvicorn

    uvicorn.run(
        "openrouter_proxy.proxy:create_app",
        host=args.host,
        port=args.port,
        factory=True,
        log_level="info",
    )


if __name__ == "__main__":
    main()