<#
.SYNOPSIS
  Write dsh-env.cmd and put a DSH shortcut on the Desktop.

.DESCRIPTION
  The launcher runs from this checkout, so there is nothing to copy and a
  `git pull` updates it. This script only does the two things that cannot be
  committed: record the paths on this machine, and create the shortcut.

  Run it again whenever a path changes; it overwrites both.

.EXAMPLE
  ./install.ps1 -DshRoot C:\src\deepseek-harness

.EXAMPLE
  ./install.ps1 -DshRoot C:\src\deepseek-harness `
                -FccDir C:\src\free-claude-code `
                -OrFreeDir C:\src\dshklv1\proxies\openrouter-free
#>
[CmdletBinding()]
param(
  # The DeepSeek Harness checkout: the directory holding apps\ and packages\.
  [Parameter(Mandatory = $true)]
  [string]$DshRoot,

  # Free Claude Code checkout, for the `free-claude` seat. Optional.
  [string]$FccDir = '',

  # This repository's proxies\openrouter-free, for the `openrouter-free` seat.
  # Optional. Defaults to the copy in this checkout when -WithOpenRouterFree
  # is given without a path.
  [string]$OrFreeDir = '',

  # Use the openrouter-free proxy shipped in this repository.
  [switch]$WithOpenRouterFree,

  # Where the launcher keeps logs and ownership markers.
  [string]$DshHome = (Join-Path $env:USERPROFILE '.dsh'),

  # Skip the Desktop shortcut.
  [switch]$NoShortcut
)
$ErrorActionPreference = 'Stop'

$scripts = $PSScriptRoot
$repo = Split-Path -Parent $scripts

if (-not (Test-Path -LiteralPath $DshRoot)) { throw "DSH_ROOT does not exist: $DshRoot" }
if (-not (Test-Path -LiteralPath (Join-Path $DshRoot 'packages'))) {
  throw "That does not look like a DeepSeek Harness checkout (no packages\): $DshRoot"
}
if ($FccDir -and -not (Test-Path -LiteralPath $FccDir)) { throw "FCC_DIR does not exist: $FccDir" }

if ($WithOpenRouterFree -and -not $OrFreeDir) {
  $OrFreeDir = Join-Path $repo 'proxies\openrouter-free'
}
if ($OrFreeDir -and -not (Test-Path -LiteralPath $OrFreeDir)) { throw "ORFREE_DIR does not exist: $OrFreeDir" }

# ---------------------------------------------------------------------------
# dsh-env.cmd
# ---------------------------------------------------------------------------
$envPath = Join-Path $scripts 'dsh-env.cmd'
$lines = @(
  '@echo off'
  'REM Generated by install.ps1. Paths on this machine; not for committing.'
  "set `"DSH_ROOT=$DshRoot`""
  "set `"FCC_DIR=$FccDir`""
  "set `"ORFREE_DIR=$OrFreeDir`""
  "set `"DSH_HOME=$DshHome`""
)
Set-Content -LiteralPath $envPath -Value $lines -Encoding ascii
Write-Output "Wrote $envPath"

if (-not (Test-Path -LiteralPath $DshHome)) {
  New-Item -ItemType Directory -Path $DshHome -Force | Out-Null
  Write-Output "Created $DshHome"
}

# ---------------------------------------------------------------------------
# Desktop shortcut
# ---------------------------------------------------------------------------
if (-not $NoShortcut) {
  $launcher = Join-Path $scripts 'launch-dsh.cmd'
  $linkPath = Join-Path ([Environment]::GetFolderPath('Desktop')) 'DSH.lnk'
  $shell = New-Object -ComObject WScript.Shell
  $link = $shell.CreateShortcut($linkPath)
  $link.TargetPath = $launcher
  # The launcher cds to DSH_ROOT itself, but starting there keeps a relative
  # path in an error message meaningful.
  $link.WorkingDirectory = $DshRoot
  $link.Description = 'Start DeepSeek Harness with its local proxies'
  $link.Save()
  Write-Output "Wrote $linkPath"
}

# ---------------------------------------------------------------------------
# What is, and is not, set up
# ---------------------------------------------------------------------------
Write-Output ''
Write-Output "DSH_ROOT    $DshRoot"
Write-Output ("FCC_DIR     " + $(if ($FccDir) { $FccDir } else { '(unset - the free-claude seat will stay off)' }))
Write-Output ("ORFREE_DIR  " + $(if ($OrFreeDir) { $OrFreeDir } else { '(unset - the openrouter-free seat will stay off)' }))
Write-Output "DSH_HOME    $DshHome"
